### ISSUE TITLE
404 Error while invoking LoggerMongo on the client side 

### ISSUE THREAD

**Issue by arlen-yu** [VeliovGroup/Meteor-logger#13]
### I'm having an issue:
Using the logger on the client side within a React component:

```javascript
import { Logger } from 'meteor/ostrio:logger'
import { LoggerMongo } from 'meteor/ostrio:loggermongo'

const log = new Logger()
new LoggerMongo(log).enable()
log.info('testing')
```

Gives me the following error: 
`Error invoking Method '1_logger_emit_Mongo': Method '1_logger_emit_Mongo' not found [404]`,
and no log is inserted into the DB.

Am I missing something? My Meteor version is 1.6.0.1, and logger versions are:

```
ostrio:logger@2.0.6
ostrio:loggerconsole@2.0.3
ostrio:loggermongo@2.0.3
```

On the server side, this error does not occur and I can see that the log is properly being inserted into the DB.

**Comment by dr-dimitru** [comment]
Hello @arlen-yu ,

Looks like you're initiating logger only on the *Client*, while *Logger* should be initiated isomorphically (e.g. on both Client and Server), for example at `lib` directory.

**Comment by arlen-yu** [comment]
@dr-dimitru perfect, thanks!

**Comment by dr-dimitru** [comment]
@arlen-yu I'm glad it was quick fix :)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-logger)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/logger)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
