### ISSUE TITLE
Remote logging (rsyslog)?

### ISSUE THREAD

**Issue by meecect** [VeliovGroup/Meteor-logger#19]
Is anyone aware of an implementation or adapter, (or instructions) for using this logging package to send messages to a remote server?  I am thinking mostly of using an rsyslog type of service. 

I am currently logging using the mongo logger but my organization has a centralized logging server that can accept syslog type messages and we have a directive to send remote logs to it from all of apps if possible.  

Thanks,
Cliff

**Comment by dr-dimitru** [comment]
Hello @meecect,

Have you found a solution to your task?
The new adapter needs to get created

**Comment by meecect** [comment]
No, I had to set that aside for the moment.  May look into again at some point in the future.
