### ISSUE TITLE
Access Collection from Client

### ISSUE THREAD

**Issue by luixal** [VeliovGroup/Meteor-logger#2]
Hi,

Can't manage to get collection from client. I'm trying to show logs using Tabular, but can't find the right collection to pass to the table.

Any ideas?

PS: I guess I could write a custom publish function, but seems quite weird since it's just a collection...

**Comment by dr-dimitru** [comment]
Hi @luixal 
1. Are we talking about collection from [logger mongo package](https://github.com/VeliovGroup/Meteor-logger-mongo)?

If so, - collection is server only, so you will need create collection on client and publish data manually, like:

``` js
log = new Logger();
var LogMongo = new LoggerMongo(log, {
  collectionName: 'AppLogs' /* Use custom collection name */
});

if (Meteor.isClient) {
  AppLogs = new Mongo.Collection('AppLogs');
  Meteor.subscribe('AppLogs');
}

if (Meteor.isServer) {
  AppLogs = LogMongo.collection;
  Meteor.publish('AppLogs', function () {
    return AppLogs.find({});
  });
}
```

**Comment by luixal** [comment]
Hi @dr-dimitru 

Yes, I was talking about logger-mongo, sorry I made a mess with the repos :(

When doing this:

``` javascript
logger = new Logger();

new LoggerMongo(
  logger,
  {
    collectionName: 'logs'
  }
).enable();

if (Meteor.isServer) {
  Logs = LoggerMongo.collection;
  Meteor.publish('Logs', function() {
    return Logs.find();
  });
}
```

I always get this

```
Exception from sub Logs id M5YuLaT2kLChuyA5N TypeError: Cannot call method 'find' of undefined
```

whenever I try to access LoggerMongo.collection. Just to clarify, the error points to the line with the `Logs.find()` as it's undefined after the `Logs = LoggerMongo.collection`.

Another problem is that for Tabular to work properly, you have to define table's structure (and collection) in common code so... no access to LoggerMongo.collection.

Still no way to get logs on the client (I'm trying to show a table with the logs) :'(

**Comment by dr-dimitru** [comment]
Sorry, my bad, you need to move that line to the `publish` block:

``` js
logger = new Logger();

var LogMongo = new LoggerMongo(
  logger,
  {
    collectionName: 'logs'
  }
).enable();

if (Meteor.isServer) {
  Meteor.publish('Logs', function() {
    var Logs = LogMongo.collection;
    return Logs.find();
  });
}
```

---

**UPDATE**: Actually there is _huge_ difference between `LogMongo` and `LoggerMongo`. When you're trying to get `collection` of `LoggerMongo` it should be `undefined`, as it's `LoggerMongo` _class_, and you need to work with `LoggerMongo` _instance_

**Comment by dr-dimitru** [comment]
Actually, I've tested previous code example on my end, and it works perfectly, here is exact code (_in coffee_):

``` coffeescript
@log     = new Logger
LogMongo = new LoggerMongo(log, collectionName: 'AppLogs')
LogMongo.enable()

if Meteor.isClient
  @AppLogs = new (Mongo.Collection)('AppLogs')
  Meteor.subscribe 'AppLogs'
if Meteor.isServer
  @AppLogs = LogMongo.collection
  Meteor.publish 'AppLogs', ->
    console.log "PUBLISH", AppLogs # <-- Collection exists here
    AppLogs.find {}
```

**Comment by dr-dimitru** [comment]
I've updated driver, now you can pass your own `Mongo.Collection` instance, now you can: 

``` js
log = new Logger;
AppLogs = new Mongo.Collection('AppLogs');

(new LoggerMongo(log, {
  collection: AppLogs
})).enable();

if (Meteor.isClient) {
  Meteor.subscribe('AppLogs');
}

if (Meteor.isServer) {
  Meteor.publish('AppLogs', function() {
    return AppLogs.find({});
  });
}
```

**Comment by luixal** [comment]
Ouch! My bad, sorry for the stupid error of using the class instead of the instance :(

Changing that didn't solve my issue as Tabular kept complaining about the collection (maybe loggerMongo uses another kind of collection or stores it in a different way?):

```
W20160522-14:26:51.650(2)? (STDERR) /home/nemesis/.meteor/packages/meteor-tool/.1.1.10.n8yu4y++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160522-14:26:51.650(2)? (STDERR)                         throw(ex);
W20160522-14:26:51.650(2)? (STDERR)                               ^
W20160522-14:26:51.660(2)? (STDERR) Error: Match error: Expected string, got object in field collectionName
W20160522-14:26:51.660(2)? (STDERR)     at check (packages/check/match.js:33:1)
W20160522-14:26:51.660(2)? (STDERR)     at new LoggerMongo (packages/ostrio_loggermongo/loggermongo.coffee:10:5)
W20160522-14:26:51.661(2)? (STDERR)     at common/lib/logger.js:21:21
W20160522-14:26:51.661(2)? (STDERR)     at /home/nemesis/dev/projects/webapps/meteor/te/.meteor/local/build/programs/server/app/common/lib/logger.js:30:4
W20160522-14:26:51.661(2)? (STDERR)     at /home/nemesis/dev/projects/webapps/meteor/te/.meteor/local/build/programs/server/boot.js:242:10
W20160522-14:26:51.661(2)? (STDERR)     at Array.forEach (native)
W20160522-14:26:51.661(2)? (STDERR)     at Function._.each._.forEach (/home/nemesis/.meteor/packages/meteor-tool/.1.1.10.n8yu4y++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160522-14:26:51.661(2)? (STDERR)     at /home/nemesis/dev/projects/webapps/meteor/te/.meteor/local/build/programs/server/boot.js:137:5
```

Anyway, with your change (you're fast, thanks!) I used my own collection and everything works like a charm:

![](http://s32.postimg.org/98v05bkmt/log_tabular.png)

PS: In case you find it useful, I can make a PR adding the tabular table definition and the screenshot to the readme :)

PS2: I've come up with a couple of FR, in case you're actively working on this, I can fill the issues in the logger-mongo repo if you want :)

**Comment by dr-dimitru** [comment]
> Anyway, with your change (you're fast, thanks!) I used my own collection and everything works like a charm

I'm glad it works :)

> In case you find it useful, I can make a PR adding the tabular table definition and the screenshot to the readme

Sure, that will be great. Or we can even add `demo` app with example.

> I've come up with a couple of FR, in case you're actively working on this, I can fill the issues in the logger-mongo repo if you want

It's on active maintenance, sure, I'll respond  to all PRs and Issues

BTW do not forget to star this package on both Atmosphere and GitHub
