### ISSUE TITLE
Log to console AND Mongo?

### ISSUE THREAD

**Issue by meecect** [VeliovGroup/Meteor-logger#21]
I created two logger instances, one for the console and one for Mongo, and often will use both throughout my code base.

What would be the best/cleanest way of defining a single object/command that logs to both locations?  I know I can just create a function that then calls both logging function, but I kinda want my invocation of the logging command to have all the features and parameters and api of this package, and I don't want to reinvent the wheel defining a bunch of functions, and I'm not proficient enough in JS to know what pattern is used in that kind of example.
 
I know this isn't a specific question related to this package and is more a generic JS question, but I thought users of this package would have some insight.

**Comment by dr-dimitru** [comment]
Hello @meecect 

Try this, let me know if that helps:

```js
const log = new Logger();

/* Activate adapters with default settings */
new LoggerMongo(log).enable();
/* meteor add ostrio:loggerconsole */
new LoggerConsole(log).enable();

log.error('error message'); // <-- will go to mongo and console

const logConsole = new Logger();
new LoggerConsole(logConsole).enable();

logConsole.error('error message'); // <-- will go to console only
```

**Comment by meecect** [comment]
Yes, this worked!  Thanks very much.
