### ISSUE TITLE
won't run on client due to Accounts being undefined

### ISSUE THREAD

**Issue by znewsham** [VeliovGroup/Meteor-logger#4]
I import Accounts as follows:
`import { Accounts } from 'meteor/accounts-base';`
I then import my logger config file:
`import './imports/api/logger.js';`
when I run the client, I get an error on `Accounts` being undefined at this location. Surely you need `Package['accounts-base'].Accounts` and not just `Accounts`

    if (Package && Package['accounts-base']) {
        Accounts.onLogin(() => {
          this.userId.set(Meteor.userId());
        });
        Accounts.onLogout(() => {
          this.userId.set(null);
        });
      }`

**Comment by dr-dimitru** [comment]
@znewsham thank you for reporting this, fixed in [`v2.0.3`](https://github.com/VeliovGroup/Meteor-logger/releases/tag/2.0.3)

Let me know how it works for you
