### ISSUE TITLE
Client side logging does not react but also no error is thrown

### ISSUE THREAD

**Issue by Gobliins** [VeliovGroup/Meteor-logger#5]
Hello, i am not so familiar with JS so i am confused about your sample code about catching the client side errors:

`const _GlobalErrorHandler = window.onerror;`

`window.onerror = (msg, url, line) => {
  log.error(msg, {file: url, onLine: line});
  if (_GlobalErrorHandler) {
    _GlobalErrorHandler.apply(this, arguments);
  }
};`

Where is the `log` coming from. Afaik i have the logger only on the serverside? Do i have to import it?

I tried importing my custom logger instance but no log is written.

**Comment by dr-dimitru** [comment]
Hello @Gobliins ,

> Where is the log coming from.

`log` comes from:
```js
const log = new Logger();
```

> Afaik i have the logger only on the serverside?

No, it's isomorphic (e.g. can run on Client and Server)

> Do i have to import it?

```js
import { Logger } from 'meteor/ostrio:logger';
const log = new Logger();

export { log };
// Then import wherever you need:
// import { log } from './path/to/file.js';
```

> I tried importing my custom logger instance but no log is written.

Which adapter are you using?
__Note:__ To use this package install an adapter *separately*:
 - [File](https://atmospherejs.com/ostrio/loggerfile) - Store application log messages into the file (FS), log rotation included;
 - [Mongo](https://atmospherejs.com/ostrio/loggermongo) - Store application log messages into MongoDB;
 - [Console](https://atmospherejs.com/ostrio/loggerconsole) - Print Client's application log messages to Server's console, messages colorized for better readability.

**Comment by Gobliins** [comment]
Hmm i see, normally it should work but i don't see any logs when logging from the client.

On Server (idLogger is just a wrapper around the ostrio logger) :
```
   //location ./imports/api/logger/
   export const idLogger = new IdLogger(new Logger());
   
   new LoggerConsole(idLogger{   format: function(opts) { ....
   })).enable({
    filter: filters,
    client: true,
    server: true,
  });
```

On client (pretty much your code):

```
// location: ./client/components/main
import { idLogger } from '/imports/api/logger/logger.js';
...
const _GlobalErrorHandler = window.onerror;

window.onerror = (msg, url, line) => {
  idLogger.error(msg, {file: url, onLine: line});

  if (_GlobalErrorHandler) {
    _GlobalErrorHandler.apply(this, arguments);
  }
};```

The onerror event is triggered correctly and i don't get an exception from the `idLogger.error` call. But nothing is logging on the meteor console.

**Comment by dr-dimitru** [comment]
I don't see you actually enable the Console Adapter, see [example here](https://github.com/VeliovGroup/Meteor-logger-console/blob/master/loggerconsole-tests.js#L11)

**Comment by Gobliins** [comment]
Updated comment. There's no problem logging on the server but when i want to log something from clientside nothing happens.

**Comment by dr-dimitru** [comment]
Well, this is weird, you should be good with this setup.
Do you have errors? On client or server?

**Comment by Gobliins** [comment]
No errors which is the funny thing. I have no exception, even surrounded the log with a try catch but no error was thrown.

So to be clear again, it is totally ok to create the logger instance on serverside and import it (and use) on the client?

**Comment by dr-dimitru** [comment]
> it is totally ok to create the logger instance on serverside and import it

No, this is not even possible.
You either create a file in a `/lib` and it runs on both *Client* and *Server*, or restrict file to *Client*.

Could you comment your code with file location and how it's being imported.

**Comment by Gobliins** [comment]
updated code

**Comment by dr-dimitru** [comment]
Okay, looks like I've got why this is happening.
The [logger](https://github.com/VeliovGroup/Meteor-logger#logger-isomorphic) and [selected adapter](https://github.com/VeliovGroup/Meteor-logger-console/#initialization-isomorphic) __must__ be registered on both *Client* and *Server*.

File in `/imports/api/` directory aren't executed by default, and must be imported in order to execute its code.

Place `import { idLogger } from '/imports/api/logger/logger.js';` under `/lib/` directory, to make sure code is executed on both, *Client* and *Server*.

Let me know if it was helpful.

**Comment by Gobliins** [comment]
> Place import { idLogger } from '/imports/api/logger/logger.js'; under /lib/ directory, to make sure code is executed on both, Client and Server.

I am not so famliar with meteors application structure but afaik it's default since meteor 1.3, to have two lib folders,  ./server/lib (which is for serverside code only) and ./client/lib.

The imports/api/* modules are imported on serverside by an import hook.

i was thinking of doing something like this: https://gist.github.com/ndastur/974acba90d319dffe87d

**Comment by dr-dimitru** [comment]
> I am not so famliar with meteors application structure but afaik it's default since meteor 1.3, to have two lib folders, ./server/lib (which is for serverside code only) and ./client/lib.

Yes, and no, there is third default - `/lib` for isomorphic code.

Since `Meteor@1.5.*` it's de facto standard to keep all code under `/imports/` directory, and use `/client/`, `/server/`, and `/lib/` only for importing right libs in right order (*Note: It's very simplified summary*).

**Comment by Gobliins** [comment]
i created the `/lib` folder inside my meteor root dir and moved the logger files into it but the behavior is the same: Logging on server works fine but logging on client nothing happens at all

also i read that `imports/api`folder is also isomorphic

**Comment by dr-dimitru** [comment]
Could you add (*for debugging purpose*) `console.log` to that file under `/lib/` directory?
```js
console.log(idLogger.log('test'));
```

 1. Post here output from Server and Client, let's see what is hapenning
 2. Post file's contents here (*which is under `/lib/` directory*)

**Comment by Gobliins** [comment]
Following code:
`logger.info('logged message')`
`console.log('inside console: ' + logger.info('logged message'));`

Gives this output:

`inside console: [logged message] 
Level: INFO; 
Details: {}; 
UserId: T3KddM8CIAvnie7LD;`

The first line does not show up at all.
The console.log, logs the content on clients log.

I have reverted my project back to have my code inside `import/api/logger/ folder` since it has made no differences. But i can do it back inside the `/lib` folder tomorrow.

**Comment by dr-dimitru** [comment]
Does it give any output on Server?

**Comment by Gobliins** [comment]
Nope, only client console.

**Comment by Gobliins** [comment]
Ok wait, i think i may have the solution but i have to be sure.
At least i managed to get now logs in both server and client even with an error message, but my code is a bit messy.

**Comment by dr-dimitru** [comment]
> Ok wait, i think i may have the solution but i have to be sure.

Sounds promising :) Keep me updated.

> At least i managed to get now logs in both server and client even with an error message, but my code is a bit messy.

I'm still thinking you're writing either Client or Server code, while you need to make it isomorphic.

**Comment by Gobliins** [comment]
It seems like it is a problem when initializing the adapters during meteor startup. So i need to add the transports right after meteor.startup is done.

**Comment by dr-dimitru** [comment]
You should be good to do this before and after `meteor.startup(/*...*/)`
When you're currently registering adapter?

**Comment by Gobliins** [comment]
> I'm still thinking you're writing either Client or Server code, while you need to make it isomorphic.

Maybe it was this. Anyways it was a problem of my code not with your logger.

Issue can be closed and thx 4 your support.

**Comment by dr-dimitru** [comment]
@Gobliins great, I'm glad it's solved.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-logger)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/logger)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
