### ISSUE TITLE
Question:Any way to log all meteor server side error?

### ISSUE THREAD

**Issue by fawzisf** [VeliovGroup/Meteor-logger#6]
Is there a way to log all Meteor or node thrown errors, similiar to using window.onerror on the client ? 
Thanks in advance for any help, and thank you the awesome repository!

**Comment by dr-dimitru** [comment]
Hello @fawzisf ,

Thank you for using this lib and for a good question (*perhaps it should be in a docs*).

Options:
 1. Listen for process' [`uncaughtException`](https://nodejs.org/api/process.html#process_event_uncaughtexception)
 2. Listen for `data` on [`process.stderr`](https://nodejs.org/api/process.html#process_process_stderr), [`process.stdin`](https://nodejs.org/api/process.html#process_process_stderr) or [`process.stdout`](https://nodejs.org/api/process.html#process_process_stdout)

Let me know if it helps.

**Comment by fawzisf** [comment]
Thank You @dr-dimitru,  it Definitely did!
One issue remains, which is catching Meteor thrown errors.
Luckily i found a solution, ill share it as  it might be a nice addition to the docs.

``` 
let originalMeteorDebug = Meteor._debug;
Meteor._debug = function (message, stack) {
        let error = new Error(message);
        error.stack = stack;
   //using an already created logger
        log.error('meteorError', error);
    return originalMeteorDebug.apply(this, arguments);
};
```

props to Kadira,from which i got this snippet 
here is the source in case anyone wants to check it in the future [Kadira's Error Handling](https://github.com/meteorhacks/kadira/blob/master/lib/hijack/error.js)

This in combination with your solution for node thrown errors would give a well rounded error tracking  server side, would love to see it in the docs!

**Comment by dr-dimitru** [comment]
@fawzisf great snippet (*missed it somehow*), do you wish to send a PR to docs?

**Comment by fawzisf** [comment]
Sure!
Will get on it right away.

**Comment by dr-dimitru** [comment]
I guess we can close this one, as #7 is merged

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue still persists on your end.
