### ISSUE TITLE
Error when using Meteor-React

### ISSUE THREAD

**Issue by maitrid** [VeliovGroup/Meteor-logger#8]
Do you have any example on using this with Meteor and React? 

When I copied lines from the sample code in the client/main.js file, an error came out: 
`Uncaught ReferenceError: LoggerFile is not defined`

Thank you!

**Comment by dr-dimitru** [comment]
Hello @maitrid ,

From the error you've referenced looks like `Logger` or `LoggerFile` is not imported.
Not sure what is so different in React from JS, *it's still JavaScript*, you [should import it this way](https://github.com/VeliovGroup/Meteor-logger-file/#es6-import):
```js
import { Logger } from 'meteor/ostrio:logger';
import { LoggerFile } from 'meteor/ostrio:loggerfile';
```

**Comment by maitrid** [comment]
Thank you, @dr-dimitru! 

I missed the 2nd import line. Now trying...After having these lines near the top of a component file:
`import { Logger } from 'meteor/ostrio:logger';
import { LoggerFile } from 'meteor/ostrio:loggerfile';
const log = new Logger();
new LoggerFile(log).enable();`

And having a `log.error("This is logger working");` inside the `render()` method. There is no output. What did I miss? Do i have to have an adaptor?

Thanks again!

**Comment by dr-dimitru** [comment]
> There is no output. What did I miss? Do i have to have an adaptor?

 1. Where you're looking for output?
 2. `LoggerFile` will put logs into the file
 3. If you want to see logs in a console - use [`LoggerConsole` adapter](https://github.com/VeliovGroup/Meteor-logger-console/)

**Comment by maitrid** [comment]
I would be looking for output in the browser console from the client code, and in the command console from server code. Will look into adapters. Thanks!

**Comment by dr-dimitru** [comment]
@maitrid Let me know what you've selected and what is working for you.
Keep me updated.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
