### ISSUE TITLE
Catch-all Meteor's errors example: [Server] issue

### ISSUE THREAD

**Issue by chafey** [VeliovGroup/Meteor-logger#9]
The supplied code snippet is never called on the server when I throw Meteor.Errors() from my meteor methods (I am using Meteor 1.6), although it is called on the client side.  Meteor._debug() is not an official API (not documented) and the source code refers to it as "temporary":

https://github.com/meteor/meteor/blob/devel/packages/meteor/debug.js#L3

I am wondering if something changed in Meteor where this no longer works.  It might be good to warn people that this could break on them.

**Comment by dr-dimitru** [comment]
Hello @chafey ,

Agree on both. But:

 0. There no such method as `Meteor.Errors`;
 1. Each section's title clearly says `example`;
 2. From n.1 grab [this example](https://github.com/VeliovGroup/Meteor-logger#catch-all-meteors-errors-example-server) and extend `Meteor.Error`, in the same manner as it's done with `._debug` in particular example;
 3. When you `throw` inside Meteor's Method (*and most of other "fibered" parts of Meteor*), it's won't interrupt Node's runtime, as Meteor will catch and handle it;
 4. "Magical" `process.stdin.resume();` will help you to catch `uncaughtException` and `unhandledRejection`.

P.S. This docs are made by other folks like you, so if you think you can add something, propose a PR. No offense.

**Comment by chafey** [comment]
Your response does not offend me, but it doesn't encourage me to contribute either.  Personally I feel this example is an anti-pattern and shouldn't be in the documentation at all.  I am posting to see if a) my understanding is correct and b) if you agree with my fix.  I am more than happy to post a PR, but I don't want to do the work if it is going to be rejected.  Can you please confirm that you are OK with me removing this example since it appears to be an anti-pattern/bad practice to depend on an undocumented API that is declared temporary and used for other purposes than Meteor.Error?  If not, please explain why you think it should stay in the documentation so I (and others) can understand your view.  Thanks

**Comment by fawzisf** [comment]
I was the one who purposed the change. 
As i agree with you that it is temporarily, it remains the only way to catch all of meteor's server side errors.
So untill an official error catching api is released this remains the best solution.
Not the prettiest solution. But it works, partially at least.

**Comment by dr-dimitru** [comment]
1. Let's keep `._debug` but mention all pros/cons;
 2. Let's add a note to `uncaughtException`, what process should be resumed and exited when async function is complete;
 3. Let's have a new example with extending `Meteor.Error`, in the same way as now it's done with `._debug`.

wdyt?

**Comment by fawzisf** [comment]
I agree, that would make it clear for everyone.

**Comment by chafey** [comment]
My issue is that the current code does not JUST log Meteor.Error, it also logs other uses of Meteor._debug().  Would you be open to changing the example to just capture and log Meteor._debug() calls (which Meteor.Error uses at least on the client side)?  Note that the current code is not logging Meteor Server errors for me at all right now

**Comment by dr-dimitru** [comment]
@chafey 

What do you exactly mean by `Meteor Server errors` ?
Unlike errors in a Browser, node.js's errors will interrupt JS runtime and should cause server to stop, or to restart.

**Comment by chafey** [comment]
My understanding of this code snippet was to automatically catch any Meteor.Error() instance that is created/thrown.  Currently in 1.6, creating a Meteor.Error() on the client will invoke Meteor._debug() which causes it to be logged.  Creating a Meteor.Error() on the server side does not do this, so it is broken in 1.6 (perhaps it worked in earlier versions - I haven't checked)

**Comment by dr-dimitru** [comment]
> perhaps it worked in earlier versions

@fawzisf have you tested it on server side on pre `meteor <= 1.5.*`?

**Comment by fawzisf** [comment]
Yes, we used it on a couple of our production apps, but as you mentioned it was interrupting the JS runtime, causing a restart. 
Haven't really used it on any 1.6 + apps just yet.

**Comment by dr-dimitru** [comment]
Hello @chafey ,

Could we close this one in favor of - https://github.com/meteor/meteor-feature-requests/issues/238 ?

//cc @mksh-su @crapthings @fawzisf

**Comment by dr-dimitru** [comment]
@chafey any news on this one?

//cc @mksh-su @crapthings @fawzisf

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
